# Generated by Django 4.2.16 on 2024-11-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_post_category_post_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pending_update',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
